export const ADD_REVIEW = 'ADD_REVIEW'
export const NEIGHBORHOOD_SELECTED = 'NEIGHBORHOOD_SELECTED'
export const FETCH_NEIGHBORHOODS = 'FETCH_NEIGHBORHOODS'
export const GET_NEIGHBORHOOD_DATA = 'GET_NEIGHBORHOOD_DATA'