export const ADD_REVIEW = 'ADD_REVIEW';
export const NEIGHBORHOOD_SELECTED = 'NEIGHBORHOOD_SELECTED';
export const FETCH_NEIGHBORHOODS = 'FETCH_NEIGHBORHOODS';
export const GET_NEIGHBORHOOD_DATA = 'GET_NEIGHBORHOOD_DATA';
export const GET_REVIEWS = 'GET_REVIEWS';
export const DEFAULT_COORDINATES = 'DEFAULT_COORDINATES';
export const UPDATE_LOGIN_STATUS = 'UPDATE_LOGIN_STATUS';
export const ZOOM = 'ZOOM';
